[k8s_masters]
k8s-master   ansible_host=192.168.0.60 node_ip=192.168.0.60

[k8s_workers]
k8s-worker-0 ansible_host=192.168.0.61 node_ip=192.168.0.61
k8s-worker-1 ansible_host=192.168.0.62 node_ip=192.168.0.62
k8s-worker-2 ansible_host=192.168.0.63 node_ip=192.168.0.63

[k8s_cluster:children]
k8s_masters
k8s_workers

[k8s_cluster:vars]
ansible_user=jose
ansible_become=true
